-- =====================================================================
-- V5 — Clientes existentes.
-- Cadastro que chegou do sistema externo de OS antes de haver migration.
-- Congelado aqui para que um banco recriado do zero já nasça utilizável:
-- ordens_servico.cliente_id é NOT NULL REFERENCES clientes (id), então sem
-- clientes não se cria nenhuma OS.
-- =====================================================================

-- clientes.id NÃO é IDENTITY (vem de fora, do sistema de OS), então o id entra
-- direto — sem OVERRIDING SYSTEM VALUE e sem sequence para ajustar, diferente
-- do que a V3 precisou fazer com processos.
--
-- DO NOTHING: no banco em uso estas linhas já existem, e o nome corrente é o
-- que o sistema externo sincronizou por último (ClienteService.sincronizar,
-- via PUT /api/clientes/{id}). Esta migration é o piso do cadastro, não a
-- fonte da verdade — preenche o que falta e não sobrescreve nada.
INSERT INTO clientes (id, nome) VALUES
    (   6, 'ATN TELECON - INF E COMERCIO LTDA'),
    (  10, 'BANTESDYL IND E COMPONENTES LTDA'),
    (  20, 'BOMAG DO BRASIL MAQUINAS LTDA'),
    (  21, 'AÇO PEÇAS DEMORE LTDA'),
    (  29, 'EXATRON INDUSTRIA ELETRONICA LTDA'),
    (  35, 'METALURGICA FALLGATTER LTDA'),
    (  37, 'HIDROTEC COM. IND. SER. HIDR. - EIRELI'),
    (  38, 'HIDROKIT INDUSTRIA E COMERCIO DE CONEXÕES LTDA'),
    (  39, 'HIDROSISTEMAS IND E COM DE EQUIPAMENTOS LTDA'),
    (  48, 'BLEISTAHL BRASIL METALURGICA LTDA'),
    (  54, 'MULT STAMP ESTAMPARIA E MATRIZARIA LTDA'),
    (  57, 'S&P BRASIL VENTILAÇÃO LTDA'),
    (  58, 'PROMETAL USINAGEM DE PRECISÃO LTDA'),
    (  59, 'PRIMUSS IND METAL TECNICA LTDA'),
    (  64, 'PARKER H. INDUSTRIA E COMERCIO LTDA'),
    (  70, 'SULPOL INDUSTRIA METALURGICA LTDA'),
    (  71, 'METALURGICA J.HARO LTDA'),
    (  73, 'TRANSTECNICA IND, COM E REPRESENTAÇÕES LTDA'),
    (  74, 'TOOLSUL INDUSTRIA METALURGICA LTDA'),
    (  76, 'METALURGICA THF IND E COMERCIO LTDA'),
    (  79, 'TAVELLI INDUSTRIA METALURGICA LTDA'),
    (  86, 'METALFEMA FERR PNEUMATICA E ELETRICA LTDA'),
    (  89, 'PERTO S/A PERIFÉRICOS PARA AUTOMAÇÃO'),
    (  92, 'MAMUTE MERCOSUL IND. E COM. LTDA'),
    (  93, 'MARIO - : METALURGICA AFJMA LTDA'),
    (  94, 'RETSUL COMERCIO DE PRODUTOS METALURGICOS LTDA'),
    ( 115, 'RACISUL AUTOMAÇÃO LTDA'),
    ( 118, 'METALFRESA INDUSTRIA METALURGICA LTDA'),
    ( 133, 'PRESET METALURGICA LTDA'),
    ( 134, 'USITRON METALURGICA LTDA'),
    ( 135, 'METALURGICA KONDAK LTDA'),
    ( 139, 'COPE & CIA LTDA'),
    ( 143, 'IMECAL IND. METAL.CANOAS LTDA'),
    ( 145, 'JULIANO PEDERSEN ROSA LTDA'),
    ( 152, 'BUCHER HIDRAULICA LTDA'),
    ( 167, 'CONMAQ IND. E COM. DE MAQUINAS LTDA'),
    ( 185, 'METALURGICA SANMARTIN - VANIR P.S. DE SOUZA L'),
    ( 192, 'FIXAR MOLAS IND COMERCIO DE ARAMADOS LTDA'),
    ( 193, 'B&B METALURGICA LTDA'),
    ( 197, 'NAVEGANTES CORTE E DOBRA LTDA'),
    ( 200, 'METALURGICA NOSSA SENHORA DOS NAVEGANTES LTDA'),
    ( 205, 'MAQUINAS SIER LTDA'),
    ( 210, 'REITZ INDUSTRIA MECANICA LTDA'),
    ( 213, 'METALURGICA BATISTA LTDA'),
    ( 215, 'BORRACHAS URANO LTDA'),
    ( 225, 'DS.MAK IND COM MAQUINAS OPERATRIZ LTDA'),
    ( 226, 'METALURGICA MEGA-SUL LTDA'),
    ( 242, 'MARBAT - GILBERTO  TEIXEIRA BATISTA'),
    ( 244, 'ARAUTERM EQUIPAMENTOS TERMO METALURGICOS LTDA'),
    ( 246, 'SPYDER - JUNKES IND. COM. LTDA'),
    ( 247, 'IDEMA PEÇAS E MAQUINAS AGRICOLAS LTDA'),
    ( 255, 'METALURGICA NUNES LTDA'),
    ( 257, 'DORVO IND E COM LTDA'),
    ( 262, 'ALESSANDRO MACHADO DA SILVA E CIA LTDA'),
    ( 267, 'RKR - RECKTENVALD & CIA LTDA'),
    ( 269, 'GLADII TECNOLOGIA EM METALURGIA LTDA'),
    ( 298, 'DJD - EQUIPAMENTOS ELETROMECÂNICOS LTDA'),
    ( 300, 'CASA DOS TOLDOS - PAULO T.S. SOUZA & CIA LTDA'),
    ( 304, 'METALURGICA REAL LTDA'),
    ( 307, 'CASA DAS CORRENTES LTDA'),
    ( 311, 'SULTECNICA INDUSTRIA MECANICA LTDA'),
    ( 323, 'GARBINOX IND E COM ARTEFATOS EM INOX LTDA'),
    ( 324, 'ABRASSER FERRAMENTAS LTDA'),
    ( 341, 'MASTHER IND. DE MAQUINAS E FERR. LTDA'),
    ( 346, 'PLASTITRES IND E COM DE PLASTICOS LTDA'),
    ( 347, 'DICTOR BLIND COMERCIO DE ACABAMENTO'),
    ( 349, 'METALURGICA RAUPP - ROGERIO RAUPP JORGE'),
    ( 355, 'HIDRABRASIL SISTEMAS HIDRAULICOS LTDA'),
    ( 359, 'FLUIDIC AUTOMAÇÃO LTDA'),
    ( 363, 'NAVEGANTES INDUSTRIA E COMERCIO LTDA'),
    ( 373, 'VINIFER INDUSTRIA E COMERCIO LTDA'),
    ( 374, 'TORNESUL TORNEARIA SUL LTDA'),
    ( 387, 'METALMORO IND COM IMP E EXP LTDA'),
    ( 395, 'ARLINDO LUDWIG & CIA LTDA'),
    ( 396, 'JP - JOSE'),
    ( 398, 'NEUMAQ MAQUINAS E EQUIPAMENTOS LTDA'),
    ( 399, 'USIAÇÃO SERVIÇOS DE TORNO E FREZA LTDA'),
    ( 414, 'MATRIFIOS FABRICAÇÃO DE MATRIZES LTDA'),
    ( 422, 'TECHNOPACK IND. COM. CONST. LTDA'),
    ( 427, 'HILTEC INDUSTRIAS METAL MECÂNICA EIRELI'),
    ( 435, 'METALURGICA FIMAC LTDA'),
    ( 436, 'PERALTA & CIA LTDA'),
    ( 462, 'ELETROFORJA INDUSTRIA MECANICA S/A'),
    ( 472, 'SMARTTECH LTDA'),
    ( 473, 'TECFRESA - VERA MARIA KUNDE ME'),
    ( 506, 'METALURGICA JOPER LTDA'),
    ( 508, 'BALLPEÇAS SUSPENSÕO E DIREÇÃO LTDA'),
    ( 516, 'PROJELMEC VENTILAÇÃO INDUSTRIAL LTDA'),
    ( 530, 'ATM-METALURGICA ATM - USI LTDA'),
    ( 534, 'METALURGICA HERFE EIRELE'),
    ( 550, 'ABEL RESTAURAÇÃO'),
    ( 552, 'SOPAMA'),
    ( 554, 'CM SOPRADORES DA SILVEIRA'),
    ( 556, 'NEXSUL INDUSTRIA E COMERCIO LTDA'),
    ( 563, 'SIGMA INDUSTRIA E COMERCIO DE FERRAMENTAS LTDA'),
    ( 575, 'BERWANGER IND E COM LTDA'),
    ( 581, 'MP - EDSON PADILHA DE OLIVEIRA'),
    ( 584, 'SUPER MAQUINAS SM COM DE MAQUINAS LTDA'),
    ( 587, 'CENTRAL DE PARAFUSOS LTDA'),
    ( 592, 'ARTSUL VALVULAS'),
    ( 593, 'SG CORTE E DOBRA CHAPAS LTDA'),
    ( 596, 'OMD TECNOLOGIA EM USINAGEM LTDA'),
    ( 602, 'TEMPERA GAÇA TRAT TERMICO DE METAIS LTDA'),
    ( 607, 'TRIVIUM USINAGEM INDUSTRIAL EIRELI'),
    ( 611, 'EIDT CIRIEX COM E IND DE SIST ELEV LTDA'),
    ( 619, 'PROMONT SOLUÇÕES LTDA'),
    ( 629, 'IMPORTHERM IMPORTAÇÃO INDUSTRIA LTDA'),
    ( 631, 'DIVERSA - INDUSTRIA METALURGICA DIVERSA LTDA'),
    ( 638, 'METALURGICA JONEVALE LTDA'),
    ( 641, 'EXPERT - WALTER PETERSEN'),
    ( 647, 'SIMKO BRASIL MONTAGENS E AUTOMACAO ME'),
    ( 665, 'FERRAMENTAS GRAN'),
    ( 669, 'TEKNO PARTS EQUIPAMENTOS INDUSTRIAIS LTDA'),
    ( 677, 'METALURGICA JAMA LTDA'),
    ( 684, 'CBC CIA BRASILEIRA DE CARTUCHOS'),
    ( 710, 'MCA METALURGICA IND E COM E SERVIÇOS LTDA'),
    ( 712, 'TTP INDUSTRIA MECANICA LTDA'),
    ( 720, 'METALURGICA MAHLER LTDA'),
    ( 733, 'AMH INDE COM DE MAQU E ASSES INDL'),
    ( 737, 'HOXI SERV INDUSTRIAIS EIRELE'),
    ( 739, 'TORQUEDO IND COM E PRESTAÇÃO DE SERVIÇOS LTDA'),
    ( 759, 'ISOARES USINAGEM LTDA'),
    ( 760, 'METALTERRA FAB PEÇAS PRECISÃO LTDA'),
    ( 762, 'KONECTY IND E COM DE INSTRUMENTOS LTDA'),
    ( 773, 'USICAST INDUSTRIA E COMERCIO LTDA'),
    ( 776, 'FMS INDÚSTRIA LTDA'),
    ( 782, 'METALURGICA SANTA LUZIA LTDA'),
    ( 785, 'VITORMAQ'),
    ( 788, 'FIRE EAGLE- PARTS IND DE ARMAS LTDA'),
    ( 789, 'SFTECH SOLUÇÕES EM USINAGEM LTDA'),
    ( 797, 'BRUNING TECNOMETAL LTDA'),
    ( 804, 'SIRIO INDUSTRIA E COMERCIO LTDA'),
    ( 818, 'HIDROENERGIA ENGENHARIA E AUTOMAÇÃO'),
    ( 830, 'IMAC - METALURGICA IMAC LTDA'),
    ( 831, 'ALTAIR URBAN'),
    ( 834, 'MENEGON - MAQUINA E PEÇAS JOSÉ MENEGON LTDA'),
    ( 837, 'METALURGICA BASSO LTDA'),
    ( 838, 'COLDBRAS SA'),
    ( 850, 'JM2 USINAGEM DE PRECISÃO INDUSTRIA E COMERCIO DE S'),
    ( 851, 'PROSOMA COMERCIO DE PEÇAS LTDA'),
    ( 860, 'FALKER AUTOMAÇÃO AGRICOLA LTDA'),
    ( 872, 'META FERRAMENTARIA'),
    ( 874, 'JRS CILINDROS HIDRAULICOS LTDA ME'),
    ( 875, 'CASA DAS RETROS LTDA'),
    ( 877, 'MRM METALURGICA LTDA'),
    ( 889, 'BALANÇA RIO GRANDE - FABIO DOS PASSOS'),
    ( 894, 'PETRO PEÇAS INDUSTRIA METALURGICA EIRELI'),
    ( 895, 'ALITON ENGENHARIA LTDA'),
    (1164, 'Metalurgica  Kondak Ltda'),
    (1188, 'COMEXI DO BRASIL LTDA'),
    (1339, 'ARBRA ENGENHARIA INDUSTRIAL LTDA'),
    (1345, 'KROETZ & KROETZ LTDA'),
    (1346, 'CONTROLFLEX EQUIPAMENTOS LTDA'),
    (1353, 'BRN Metal Industria e Comercio LTDA'),
    (1358, 'SPYDER INDUSTRIA E COMERCIO DE COMPONENTES ELETRON'),
    (1360, 'JCN INDUSTRIA E COMERCIO EIRELLI'),
    (1366, 'ROLETEK BRASIL INDUSTRIA E COMERCIO DE ROLETES LTD'),
    (1368, 'C E C CORRENTES INDUSTRIAIS LTDA'),
    (1369, 'FLEXMASTER-FMC INDUSTRIA DE EQUIP ELETRICOS LTDA'),
    (1371, 'CERTA USINAGEM LTDA ME'),
    (1382, 'CORRENTEC IND METALURGICA LTDA.'),
    (1386, 'FACI SERVICE FORNEC. E MONYAG. INDL LTDA'),
    (1390, 'TECMOLD INDUSTRIA E COMERCIO LTDA'),
    (1391, 'ELEVAR CARGAS COMERCIO VAREJISTA DE FERR EIRELE ME'),
    (1397, 'NC CONTROL ASSISTENCIA TECNICA E COM DE PEÇAS LTDA'),
    (1399, 'METALURGICA RIAJ LTDA'),
    (1406, 'USINTER FABRICAÇÃO DE PEÇAS E DISP PARA IND EIRELI'),
    (1407, 'UNIPECAS CORRENTES E ACESSORIOS LTDA'),
    (1417, 'PREMIUM FLEX LTDA'),
    (1420, 'IMER EROSAO IND. COM. BENEF. IMP. EXP. E'),
    (1422, 'TKR USINAGEM INDUSTRIAL EIRELI'),
    (1443, 'GDS'),
    (1444, 'SIMEROS PROJETOS ELETROMECANICOS LTDA'),
    (1446, 'IMEX METALURGICA LTDA'),
    (1449, 'EPR ESTRUTURAS METALICAS'),
    (1454, 'SUPI - HAMILTON DA SILVA PIRES'),
    (1459, 'LOEWE SERVICO E COMERCIO EIRELI - ME'),
    (1462, 'ENGEMOLD - CONSTRUTORA ESTRUTURAS PRE-FABRICADAS'),
    (1474, 'GREPOL ENGENHARIA E CONSTRUCOES LTDA'),
    (1475, 'J.SUL SERVIÇOS - JAIMER MARSAL GRASEL'),
    (1481, 'VM - VANESSA MENEGOTTO SIQUEIRA'),
    (1490, 'PREMUNDI TORNEADOS DE PRECISAO LTDA'),
    (1492, 'IPAR USINAGEM E PROJETOS LTDA'),
    (1497, 'TORNEARIA CASTELO - SILVA & PIRES SERVIÇOS DE TORN'),
    (1498, 'INTERFORMA EQUIPAMENTOS LTDA'),
    (1502, 'MADEF - INDUSTRIA DE EQUIPAMENTOS DE REFRIGERAÇÃO'),
    (1504, 'GD DIESELCOM DE MAQUINAS E PEÇAS PARA LINHA DIESEL'),
    (1525, 'DESENVOLTECH METALURGICA LTDA'),
    (1528, 'DATAPACK MAQUINAS INDUSTRIAIS LTDA - ME'),
    (1535, 'SUPREMOSUL- METALURGICA SUPREMO SUL EIRELI'),
    (1538, 'ARCO REPARACAO E MANUTENCAO INDL EIRELI'),
    (1539, 'SPINTEC TECNOLOGIA COM., SERVIÇOS E REPAROS EM MAQ'),
    (1543, 'BENFATO USINAGEM'),
    (1544, 'MATRI INDUSTRIA METALURGICA LTDA'),
    (1545, 'SNAP AUTOMAÇÃO INDUSTRIAL LTDA'),
    (1548, 'TRIVIUM FL02'),
    (1549, 'GRAKO ENGENHARIA LTDA'),
    (1552, 'FERRAMENTARIA AUGUST LTDA'),
    (1553, 'RESTART IND COM IMP EXP EQUI AC. ELET. LTDA'),
    (1555, 'OTIMIZE IND E COM DE SERVICOS LTDA'),
    (1558, 'JL SOLDAS INDUSTRIA METAL LTDA'),
    (1561, 'FORTEACO INDUSTRIA METALURGICA EIRELI'),
    (1562, 'DIFER - D ROIS M CANDIDO'),
    (1570, 'B&M METALURGICA LTDA'),
    (1574, 'AR500 BRASIL- INDUSTRIA DE ALVOS LTDA'),
    (1583, 'WITT USINAGEM E MATRIZARIA LTDA'),
    (1585, 'WILLIAN MARTINS DOS SANTOS'),
    (1588, 'MAREL - JBT MAREL BRASIL LTDA'),
    (1593, 'VIEMAR INDUSTRIA E COMERCIO LTDA'),
    (1600, 'EKS RAG IND METALMECANICA LTDA'),
    (1605, 'Payback projetos e montagem eletronicas LTDA'),
    (1606, 'PETER LUIZ KLEGUES DE MATOS'),
    (1617, 'HIDRAUCON COM DE MANG CONEX HIDRAUL E PNEUM LTDA.'),
    (1618, 'TECMETAL ESTAMPARIA E USINAGEM LTDA'),
    (1620, 'QUANTUM ENG MONT INDL LTDA'),
    (1626, 'ABP EQUIPAMENTOS LTDA'),
    (1628, 'FUEL INJECT - MANUTENCAO DE SISTEMAS DE INJECAO DE'),
    (1633, 'ALFA SISTEMAS AUTOMOTIVOS LTDA'),
    (1636, 'GABE E PASTRO INDUSTRIA E COMERCIO DE EQUIPAMENTOS'),
    (1637, 'SS USINAGEM LTDA'),
    (1638, 'INDHIPA INDUSTRIA E COMERCIO LTDA'),
    (1640, 'METALURGICA R-MAC LTDA.'),
    (1646, 'HB ANDERSON'),
    (1648, 'MENDES MAQUINAS LTDA'),
    (1650, 'MAZA INDUSTRIA METALURGICA LTDA'),
    (1651, 'STEFLE INDUSTRIA METALURGICA LTDA'),
    (1674, 'ASERVE MANUTENCOES INDUSTRIAIS LTDA'),
    (1676, 'S.L. VAZADORES LTDA'),
    (1677, 'SAF-HOLLAND DO B RASIL INDUSTRIA EPRODUÇÃO DE EIXO'),
    (1678, 'DKF TECNOLOGIA INDUSTRIA E COMERCIO DE EQUIPAMENTO'),
    (1679, 'INFINITY EQUIPAMENTOS E FERRAMENTAS LTDA'),
    (1681, 'JL LASER INOVACOES EM ACO LTDA'),
    (1685, 'TRACTION INDL LTDA'),
    (1694, 'IDEAL MOLDES & MATRIZES LTDA'),
    (1695, 'TOCO Ademar L. Disconsi & Cia Ltda - ME'),
    (1697, 'SIRIO COM DE MAQ E EQUIP INDUSTRIAIS LTDA'),
    (1699, 'VIHAMAR  - ADRIANE AMARAL VIANA'),
    (1701, 'USIMER SERVICOS DE USINAGEM LTDA'),
    (1703, 'FSK - F. SCHWANKE KRANTTECHNIK LTDA'),
    (1705, 'COHIPA - COMERCIAL HIDRO PNEUMATICA LTDA'),
    (1709, 'STARKPACK Comercio de Embalagens e ImportaÇÃO Ltda'),
    (1710, 'CASA BRON IND E COM DE PERSIANAS E TELAS DE PROJEC'),
    (1714, 'Rodovale Industria e Comercio de Equipamentos Rodo'),
    (1721, 'MOINHO ESTRELA LTDA'),
    (1725, 'METALURGICA LP USITEC LTDA'),
    (1728, 'SEQUENCIAL MILIMETRICA IND.DE EQUIP.ORTOP.LTDA'),
    (1729, 'TORNEARIA GODOIS - IRENE GODOIS DA SILVA LTDA.'),
    (1732, 'CF MARTINS'),
    (1733, 'Metalúrgica Baruna Ind. e Comércio Ltda.'),
    (1735, 'HR KOMPRESS SOLUCOES INDUSTRIAIS LTDA'),
    (1736, 'F&F COMERCIO E SERVICOS ESPORTIVOS LTDA'),
    (1737, 'METALURGICA CATTO LTDA'),
    (1741, 'MOPO ZNC Indústria e Comércio de Artefatos Metálic'),
    (2741, 'AGTN METALURGICA LTDA'),
    (2745, 'DRAYTON AEROSPACE SA'),
    (2746, 'SULFASE COM DE MATERIAIS DE CONSTRUÇÃO E FERRAGENS'),
    (3747, 'SANDRO PETRY'),
    (3749, 'ACOTEC INDUSTRIA DE PECAS PARA MAQUINAS LTDA.'),
    (3752, 'PAYBACK CONSULTORIA LTDA'),
    (4754, 'MEZAS MOBILIARIO CONTEMPORANEO LTDA ME'),
    (4756, 'RETISUL RETIFICA INDUSTRIAL LTDA'),
    (4757, 'SENSOR COMERCIO DE PECAS E EQUIPAMENTOS INDUSTRIAI'),
    (4758, 'VMS INDUSTRIA E COMERCIO DE PECAS AGRICULAS LTDA'),
    (4759, 'TK ELEVADORES BRASIL LTDA'),
    (5760, 'HIAB BRASIL GUINDASTES E SERVICOS LTDA'),
    (5761, 'MENDEL SERVICOS DE USINAGEM LTDA'),
    (5764, 'MD SERVICOS DE USINAGEM LTDA.-ME'),
    (5766, 'MZR LASER STEEL LTDA'),
    (5767, 'RS IND ELETRONICA LTDA'),
    (5768, 'ARLANXEO Brasil S.A.'),
    (5777, 'MAK STEEL INDUSTRIA E COMERCIO LTDA ME'),
    (5780, 'BONAFER INDUSTRIA E COMERCIO DE MAQUINAS E EQUIPAM'),
    (5781, 'GUIMARAES BRASIL IND ALIM LTDA'),
    (5782, 'COL EVANGELICO PANAMBI ESCOLA DE 1 E 2 GRAUS'),
    (5783, 'SERGIO ANDRE MUSA - EIRELI'),
    (5788, 'CALVALTEC INDUSTRIA DE MAQUINAS LTDA'),
    (5799, 'Metalurgica Manzato Ltda.'),
    (5802, 'JA INDL LTDA'),
    (5803, 'RB USINAGEM LTDA'),
    (5808, 'DORVO INDUSTRIA E COMERCIO LTDA'),
    (5816, 'MATRISUL INDUSTRIA METALURGICA EIRELI'),
    (5818, 'ESC IND. E COM. DE ART. DE BOR. LTDA'),
    (5819, 'GAP SOLUCOES EM CORTE A FIO LTDA'),
    (5835, 'Casa das Correntes Ind e Com S/A'),
    (5861, 'ENVIEL INDUSTRIAL LTDA'),
    (5863, 'BOSCARDIN E NASCIMENTO LTDA'),
    (5889, 'ZENNER DO BRASIL INSTRUMENTOS DE MEDICAO LTDA'),
    (5914, 'MAXITOOLS IMPORTACAO EXPORTACAO'),
    (5933, 'SAUR EQUIPAMENTOS S/A.'),
    (5940, 'EZATA INDUSTRIAL LTDA'),
    (5949, 'RER PARTS LTDA')
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------- processos
-- Processos de rotina dos setores, na ordem em que a peça passa por eles.
-- Diferente do 'Desengraxante(Inicio)' da V3, estes são cadastro comum: o id
-- vem da identity, sem OVERRIDING SYSTEM VALUE e sem faixa reservada.
--
-- WHERE NOT EXISTS em vez de INSERT direto: o banco em uso já roda há tempo e
-- estes processos podem ter sido cadastrados pela tela (ProcessoService.criar).
-- Não há unique em processos.descricao, então nada no banco barraria a
-- duplicata — a guarda tem que estar aqui. Mesmo espírito do DO NOTHING dos
-- clientes: esta migration é o piso do cadastro, não a fonte da verdade.
INSERT INTO processos (descricao, etapa)
SELECT t.descricao, t.etapa
FROM (VALUES
    -- oxidação
    ('DECAPAGEM OX/FOS',     'PRE_TRATAMENTO'),
    ('OXIDAÇÃO NEGRA',       'TRATAMENTO'),
    ('FOSFATO DE MANGANÊS',  'TRATAMENTO'),
    ('AGUA QUENTE',          'POS_TRATAMENTO'),
    ('ÓLEO/OLEAMENTO',       'POS_TRATAMENTO'),
    -- zinco
    ('DECAPAGEM ZN',         'PRE_TRATAMENTO'),
    ('DESENGRAXANTE ELETRO', 'PRE_TRATAMENTO'),
    ('ZINCO ALCALINO',       'TRATAMENTO'),
    ('ZINCO ACIDO',          'TRATAMENTO'),
    ('ATIVAÇÃO',             'POS_TRATAMENTO'),
    ('CROMATO TRIVALENTE',   'POS_TRATAMENTO')
) AS t(descricao, etapa)
WHERE NOT EXISTS (SELECT 1 FROM processos p WHERE p.descricao = t.descricao);

-- Sem tag_id: quem grava a tag é a tela, quando o leitor for pareado ao tanque.
-- ux_processos_tag é índice parcial (WHERE tag_id IS NOT NULL), então os NULLs
-- não conflitam entre si.

-- As posições vêm num INSERT separado, e não via CTE com RETURNING, justamente
-- por causa da guarda acima: RETURNING só devolve o que foi de fato inserido,
-- então um processo que já existia sairia da CTE sem ganhar posição nenhuma.
-- Buscando por descricao, o vínculo é feito valha o processo novo ou antigo.
-- ON CONFLICT DO NOTHING apoia-se na PK (processo_id, posicao).

-- Os cinco de oxidação rodam só na oxidação.
INSERT INTO processo_posicoes (processo_id, posicao)
SELECT p.id, 'OXIDACAO'
FROM processos p
WHERE p.descricao IN (
    'DECAPAGEM OX/FOS',
    'OXIDAÇÃO NEGRA',
    'FOSFATO DE MANGANÊS',
    'AGUA QUENTE',
    'ÓLEO/OLEAMENTO'
)
ON CONFLICT DO NOTHING;

-- Os seis do zinco são UM processo cada, rodando em DOIS setores — não dois
-- cadastros de mesmo nome. É para isso que processo_posicoes existe (N posições
-- por processo, Processo.posicoes é um Set<Posicao>); duplicar a linha em
-- processos deixaria a tela com nomes repetidos e partiria o histórico do
-- mesmo tanque em dois ids.
INSERT INTO processo_posicoes (processo_id, posicao)
SELECT p.id, pos.posicao
FROM processos p
CROSS JOIN (VALUES ('PENDURADO'), ('AUTOMATICA')) AS pos(posicao)
WHERE p.descricao IN (
    'DECAPAGEM ZN',
    'DESENGRAXANTE ELETRO',
    'ZINCO ALCALINO',
    'ZINCO ACIDO',
    'ATIVAÇÃO',
    'CROMATO TRIVALENTE'
)
ON CONFLICT DO NOTHING;

-- --------------------------------------------------------------- operadores
-- Os dois admins iniciais, para que um banco recriado do zero tenha por onde
-- entrar. Mesma guarda dos processos, e pela mesma razão: operadores.nome não
-- tem unique, então rodar num banco que já os tem criaria um segundo 'Cauan'.
-- tag_id fica NULL — a tag é pareada depois, pela tela.
INSERT INTO operadores (nome, permissao)
SELECT t.nome, t.permissao
FROM (VALUES
    ('Márcio', 'ADMIN'),
    ('Cauan',  'ADMIN')
) AS t(nome, permissao)
WHERE NOT EXISTS (SELECT 1 FROM operadores o WHERE o.nome = t.nome);


-- ---------------------------------------------------------------- cargas
INSERT INTO public.cargas (nome, tipo, posicao)
SELECT t.nome, t.tipo, t.posicao
FROM (VALUES
    ('T 01', 'TRAVE',  'PENDURADO'),
    ('T 02', 'TRAVE',  'PENDURADO'),
    ('T 03', 'TRAVE',  'PENDURADO'),
    ('T 04', 'TRAVE',  'PENDURADO'),
    ('T 05', 'TRAVE',  'PENDURADO'),
    ('T 06', 'TRAVE',  'PENDURADO'),
    ('T 07', 'TRAVE',  'PENDURADO'),
    ('T 08', 'TRAVE',  'PENDURADO'),
    ('T 09', 'TRAVE',  'PENDURADO'),
    ('T 10', 'TRAVE',  'PENDURADO'),
    ('T 11', 'TRAVE',  'PENDURADO'),
    ('T 12', 'TRAVE',  'PENDURADO'),
    ('T 13', 'TRAVE',  'PENDURADO'),
    ('T 14', 'TRAVE',  'PENDURADO'),
    ('T 15', 'TRAVE',  'PENDURADO'),
    ('T 16', 'TRAVE',  'PENDURADO'),
    ('T 17', 'TRAVE',  'PENDURADO'),
    ('T 18', 'TRAVE',  'PENDURADO'),
    ('T 19', 'TRAVE',  'PENDURADO'),
    ('T 20', 'TRAVE',  'PENDURADO'),
    ('T 21', 'TRAVE',  'PENDURADO'),
    ('T 22', 'TRAVE',  'PENDURADO'),
    ('T 23', 'TRAVE',  'PENDURADO'),
    ('T 24', 'TRAVE',  'PENDURADO'),
    ('T 25', 'TRAVE',  'PENDURADO'),
    ('T 26', 'TRAVE',  'PENDURADO'),
    ('T 27', 'TRAVE',  'PENDURADO'),
    ('T 28', 'TRAVE',  'PENDURADO'),
    ('T 29', 'TRAVE',  'PENDURADO'),
    ('T 30', 'TRAVE',  'PENDURADO'),
    ('C 01', 'CESTO',  'OXIDACAO'),
    ('C 02', 'CESTO',  'OXIDACAO'),
    ('C 03', 'CESTO',  'OXIDACAO'),
    ('C 04', 'CESTO',  'OXIDACAO'),
    ('C 05', 'CESTO',  'OXIDACAO'),
    ('C 06', 'CESTO',  'OXIDACAO'),
    ('C 07', 'CESTO',  'OXIDACAO'),
    ('C 08', 'CESTO',  'OXIDACAO'),
    ('C 09', 'CESTO',  'OXIDACAO'),
    ('C 10', 'CESTO',  'OXIDACAO'),
    ('T 01', 'TAMBOR', 'AUTOMATICA'),
    ('T 02', 'TAMBOR', 'AUTOMATICA'),
    ('T 03', 'TAMBOR', 'AUTOMATICA'),
    ('T 04', 'TAMBOR', 'AUTOMATICA'),
    ('T 05', 'TAMBOR', 'AUTOMATICA'),
    ('T 06', 'TAMBOR', 'AUTOMATICA'),
    ('T 07', 'TAMBOR', 'AUTOMATICA'),
    ('T 08', 'TAMBOR', 'AUTOMATICA'),
    ('T 09', 'TAMBOR', 'AUTOMATICA'),
    ('T 10', 'TAMBOR', 'AUTOMATICA')
) AS t(nome, tipo, posicao)
WHERE NOT EXISTS (
    SELECT 1 FROM cargas c WHERE c.nome = t.nome AND c.tipo = t.tipo
);
